# config.toml

[mcmc]
iterations = 5000
burn_in = 500
# initial_theta overrides other parameters.
# if a parameter is set here, then it will
# be estimated by MCMC. The value set here
# will override the filter_params below.
initial_theta = [{'beta_mu' = 0.05},
                 {'beta_mu' = 0.1},
                 {'beta_mu' = 0.15}]

unif_prior = [0.03, 0.25]

# file_label is appended to output file names
file_label = "beta_mu_test"

[filter_params]
num_particles = 150
dt = 1.0
seed_size = 0.03
dispersion = 30
beta_prior = [0.001, 0.05]

[model_params]
gamma = {value = 0.06, is_fixed = true}
mu = {value = 0.004, is_fixed = true}
q = {value = 0.1, is_fixed = true}
eta = {value = 0.1, is_fixed = true}
std = {value = 10.0, is_fixed = true}
R = {value = 50.0, is_fixed = true}
hosp = {value = 10, is_fixed = true}
L = {value = 90, is_fixed = true}
D = {value = 10, is_fixed = true}
dW_volatility = {value = 0.01, is_fixed = true}

# Params for the beta OU process
beta_theta = {value = 1, is_fixed = true}
beta_mu = {value = 0.15, is_fixed = true}
beta_sigma = {value=0.01, is_fixed = true}

[logging]
level = "INFO"
